// Home Actions
export const CHANGE_TITLE = 'CHANGE_TITLE'
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'
export const SET_NORMAL_EVENTS = 'SET_NORMAL_EVENTS'

// Event Actions
export const ADD_EVENT = 'ADD_EVENT'
export const SET_MODAL_OPEN = 'SET_MODAL_OPEN'
export const SET_EVENT_MODAL = 'SET_EVENT_MODAL'
export const SET_ACTIVE_EVENT = 'SET_ACTIVE_EVENT'
export const DELETE_EVENT = 'DELETE_EVENT'
export const SET_EDIT_MODAL = 'SET_EDIT_MODAL'
export const SET_CONFIRM_MODAL = 'SET_CONFIRM_MODAL'
export const SAVE_EDIT = 'SAVE_EDIT'
export const SET_CONFIRM_ADDITION = 'SET_CONFIRM_ADDITION'
export const SET_CONFIRM_EDIT = 'SET_CONFIRM_EDIT'