const TempEvents = [
  {
    'allDay': false,
    'emotion': 'happy',
    'end': new Date(),
    'energy': 2,
    'start': new Date(),
    'text': 'test paragraph text',
    'title': 'Test Event',
    'type': 'school',
  },
  {
    'allDay': false,
    'emotion': 'happy',
    'end': new Date(),
    'energy': 2,
    'start': new Date(),
    'text': 'This is another test event',
    'title': 'Test Event 2',
    'type': 'school',
  },
  {
    'allDay': false,
    'emotion': 'happy',
    'end': new Date(2016, 11, 5),
    'energy': 2,
    'start': new Date(2016, 11, 1),
    'text': 'Some event on this day',
    'title': 'Test Event 3',
    'type': 'school',
  },
  {
    'allDay': false,
    'emotion': 'sad',
    'end': new Date(2016, 10, 15),
    'energy': 2,
    'start': new Date(2016, 10, 12),
    'text': 'Some flavorful description',
    'title': 'Test Event 4',
    'type': 'work',
  },
  {
    'allDay': false,
    'emotion': 'sad',
    'end': new Date(2016, 10, 25),
    'energy': 2,
    'start': new Date(2016, 10, 25),
    'text': 'Some flavorful description',
    'title': 'Test Event 5',
    'type': 'work',
  },
  {
    'allDay': false,
    'emotion': 'sad',
    'end': new Date(2016, 10, 25),
    'energy': 2,
    'start': new Date(2016, 10, 25),
    'text': 'Some flavorful description',
    'title': 'Test Event 6',
    'type': 'work',
  },
  {
    'allDay': false,
    'emotion': 'sad',
    'end': new Date(2016, 10, 22),
    'energy': 2,
    'start': new Date(2016, 10, 21),
    'text': 'Some flavorful description',
    'title': 'Test Event 7',
    'type': 'work',
  }
]

export default TempEvents