const TempEvents = [
  {
    'allDay': false,
    'emotion': 'happy',
    'end': new Date(),
    'energy': 3,
    'start': new Date(),
    'text': 'This is a leisurely and pleasant event',
    'title': 'Lunch with Friend',
    'type': 'leisure',
  },
  {
    'allDay': false,
    'emotion': 'angry',
    'end': new Date(),
    'energy': 4,
    'start': new Date(),
    'text': 'This is an unnecessary meeting',
    'title': '2 Hour Meeting',
    'type': 'school',
  },
  {
    'allDay': false,
    'emotion': 'happy',
    'end': new Date(2016, 11, 11),
    'energy': 3,
    'start': new Date(2016, 11, 11),
    'text': 'No school on this day',
    'title': 'No school',
    'type': 'school',
  },
  {
    'allDay': false,
    'emotion': 'sad',
    'end': new Date(2016, 10, 15),
    'energy': 2,
    'start': new Date(2016, 10, 12),
    'text': 'Some flavorful description',
    'title': 'Test Event 4',
    'type': 'work',
  },
  {
    'allDay': false,
    'emotion': 'excited',
    'end': new Date(2016, 10, 25),
    'energy': 2,
    'start': new Date(2016, 10, 25),
    'text': 'Some flavorful description',
    'title': 'Test Event 5',
    'type': 'leisure',
  },
  {
    'allDay': false,
    'emotion': 'sad',
    'end': new Date(2016, 10, 25),
    'energy': 1,
    'start': new Date(2016, 10, 25),
    'text': 'Some flavorful description',
    'title': 'Test Event 6',
    'type': 'work',
  },
  {
    'allDay': false,
    'emotion': 'happy',
    'end': new Date(2016, 10, 22),
    'energy': 2,
    'start': new Date(2016, 10, 21),
    'text': 'Some flavorful description',
    'title': 'Test Event 7',
    'type': 'work',
  }
]

export default TempEvents